# Generated by Django 6.0.3 on 2026-03-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=10)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('plan', models.CharField(choices=[('scanner', 'Scanner Automotriz'), ('completa', 'Inspección Completa 360°'), ('promo_2x1', 'Promo 2x1 Inspección Completa')], default='scanner', max_length=20)),
                ('monto', models.IntegerField(default=0)),
                ('metodo_pago', models.CharField(choices=[('flow', 'Pago Online (Flow)'), ('presencial', 'Pago Presencial')], default='flow', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('followup_enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
